---
# This file has the custom configurations for:
# configure_git

# Variables related to "configure_git" module
user_git_file: "{{ ansible_facts['user_dir'] }}/.gitconfig"

# These are settings for the "user" section inside the git config file.
# This can be easily extended to other sections too, if necessary.
git_user_config:
  - { enabled: True,  state: 'present',
      section: 'user', parameter: 'name', value: '{{ git_username }}' }
  - { enabled: True,  state: 'present',
      section: 'user', parameter: 'email', value: '{{ git_email }}' }
  - { enabled: True,  state: 'present',
      section: 'core', parameter: 'editor', value: '{{ git_editor }}' }
  - { enabled: True,  state: 'present',
      section: 'core', parameter: 'autocrlf', value: '{{ git_autocrlf }}' }
...